name: Reusable Deploy
on: workflow_call
jobs:
  build:

    runs-on: self-hosted
    container:
      image: ubuntu:latest # container to run inside
    steps:
      - name: Output information
        run: echo "This is a reusable workflow for deployment!"
