name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: false
        type: string
        default: dist
    outputs:
      deploy-info:
        description: 'Information about the deploy step'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ step.set-results.outputs.step-results }}
    runs-on: self-hosted
    container:
      image: ubuntu:latest # container to run inside
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List hashFiles
        run: ls -lah
      - name: Output information
        run: echo "This is a reusable workflow for deployment!"
      - name: Set result outputs
        id: set-results
        run: echo "::set-output name=step-results::success"
